### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by Rishabh4275**
Reads the whole name of the manga rather than just the first word.

### CODE REVIEW

**Comment by Rishabh4275** [comment]
It didn't accept manga names bigger than a single word.

**Comment by jiaweihli** [comment]
It looks like you might be using different whitespace, can you revert that to format the diff to only show your changes?  I'm having a little trouble identifying the fix here.

**Comment by Rishabh4275** [comment]
so basically in the manga.py where it is
for manga in args:
    over here it takes it as a list rather than a string and str(args) doesn't work nor does removing the loop all together .

so 
x=[1]
for manga in x:
    manga=str(args)

this takes the whole name and runs the loop only once.

**Comment by CharlieCorner** [comment]
I think that before we can move forward with the code review, it'd be better if you do what @jiaweihli is suggesting. It'd seem like you formatted your whole code and now your diff shows that every single line has changed.

I have three more suggestions that would help the code review, if I may:

1. I'm seeing that even though your fork was made from a104fb2fc33ae0f578e99fa8828239ea5c50caa1, you are missing the changes from 72c09ace77adb9fb4d7f50098f4a7b7474d7d723 through d195e405761210cf00e60a38c4b6cdeac90ac4f5 which add the Tankoubon functionality. Could it be that you manually copied and pasted your changes for the whole file and overwrote those changes? This will become evident once you revert your whitespace changes as @jiaweihli is saying.
2. It is not really clear what you are trying to fix in this Pull Request, your title states that you want to "Add files via upload" but from what I'm getting in the comments and the few changes I can distinguish, you actually wanted to add support to get mangas with more than one word in the name. So which is which?
3. manga_downloader supports specifying more than one manga per download session, are you sure you are not breaking this with your change? This is not really evident because the diff is messed up, but it looks like you are removing the ability to read multiple mangas and just taking the first one.

**Comment by CharlieCorner** [comment]
By the way, manga_downloader already supports mangas with more than one word in the name, you just need to enclose them in quotes:

`python manga.py -d /home/myuser/mangas "shingeki no kyojin" bleach naruto`

This will instruct manga_downloader to look for the three mangas, Shingeki no Kyojin, Bleach and Naruto and will download all chapters individually.

I just tested this in both Windows and Linux successfully using the latest master branch code.

From this, and unless anybody has any objections, I think we can close the Pull Request @jiaweihli, I don't think we need to merge or do anything else here.

**Comment by jiaweihli** [comment]
Yup, it sounds like what @CharlieCorner suggested should fix your issue @Rishabh4275.
Please re-open if you're still running into any issues!

**Pull request closed without merging**
